-- completions: emit shell completion scripts for moonraker.
--
-- Pure Lua port of mainsail's completions.py. The scripts call back into
-- the running binary (`moonraker --list`) to enumerate applets at
-- completion time, so they never go stale.

local common = require("common")

local NAME = "completions"

local BASH = [=[# bash completion for moonraker (and the moonraker-X aliases)
# Generated by `moonraker completions bash`.
_moonraker_complete() {
    local cur prev words cword
    _init_completion || return

    local prog="$(basename -- "${words[0]}")"
    if [ "$prog" = "moonraker" ]; then
        if [ "$cword" -eq 1 ]; then
            local applets
            applets=$("${words[0]}" --list 2>/dev/null \
                | awk '{print $1}' \
                | grep -v '^$')
            applets+=" --list --help --version"
            COMPREPLY=( $(compgen -W "$applets" -- "$cur") )
            return
        fi
    fi
    _filedir
}
complete -F _moonraker_complete moonraker
]=]

local ZSH = [=[#compdef moonraker
# zsh completion for moonraker.
# Generated by `moonraker completions zsh`.

_moonraker() {
    local -a applets
    if (( CURRENT == 2 )); then
        local raw
        raw=$(moonraker --list 2>/dev/null)
        applets=( ${(f)"$(echo "$raw" | awk '{print $1}')"} )
        applets+=( --list --help --version )
        _describe -t applets 'applet' applets
        return
    fi
    _files
}

_moonraker "$@"
]=]

local FISH = [=[# fish completion for moonraker.
# Generated by `moonraker completions fish`.

complete -c moonraker -n '__fish_is_first_token' -f \
    -a "(moonraker --list 2>/dev/null | string trim | string replace -r '\\s+.*$' '')" \
    -d 'applet'

complete -c moonraker -n '__fish_is_first_token' -l list -d 'list applets'
complete -c moonraker -n '__fish_is_first_token' -l help -d 'show help'
complete -c moonraker -n '__fish_is_first_token' -l version -d 'show version'

complete -c moonraker -n 'not __fish_is_first_token' -F
]=]

local POWERSHELL = [=[# PowerShell completion for moonraker.
# Generated by `moonraker completions powershell`.
# Add to your $PROFILE, or pipe directly: . (moonraker completions powershell | Out-String)

Register-ArgumentCompleter -Native -CommandName moonraker -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements
    if ($tokens.Count -le 2) {
        $applets = & moonraker --list 2>$null |
            ForEach-Object { ($_ -split '\s+')[1] } |
            Where-Object { $_ }
        $applets += @('--list', '--help', '--version')
        $applets |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', $_
                )
            }
    }
}
]=]

local GENERATORS = {
  bash = BASH,
  zsh = ZSH,
  fish = FISH,
  powershell = POWERSHELL,
  pwsh = POWERSHELL,
}

local function main(argv)
  local args = {}
  for i = 1, #argv do args[i] = argv[i] end

  if #args == 0 then
    common.err(NAME, "shell required: bash, zsh, fish, or powershell")
    return 2
  end

  local shell = args[1]:lower()
  local body = GENERATORS[shell]
  if not body then
    common.err(NAME, "unknown shell: " .. args[1] .. ". choose: bash, zsh, fish, powershell")
    return 2
  end
  io.stdout:write(body)
  io.stdout:flush()
  return 0
end

return {
  name = NAME,
  aliases = {},
  help = "emit shell completion scripts (bash/zsh/fish/powershell)",
  main = main,
}
