local helpers = require("helpers")

describe("cli dispatcher", function()
  before_each(function()
    helpers.load_applets()
  end)

  describe("wrapper mode", function()
    it("prints top-level help with no args", function()
      local rc, out = helpers.invoke_wrapper()
      assert.equal(0, rc)
      assert.is_truthy(out:match("Usage:"))
      assert.is_truthy(out:match("moonraker <applet>"))
    end)

    it("prints version", function()
      local rc, out = helpers.invoke_wrapper("--version")
      assert.equal(0, rc)
      assert.is_truthy(out:match("^moonraker %d+%.%d+%.%d+"))
    end)

    it("prints applet list with --list", function()
      local rc, out = helpers.invoke_wrapper("--list")
      assert.equal(0, rc)
      assert.is_truthy(out:match("echo"))
      assert.is_truthy(out:match("pwd"))
      assert.is_truthy(out:match("true"))
      assert.is_truthy(out:match("false"))
    end)

    it("dispatches to a known applet", function()
      local rc, out = helpers.invoke_wrapper("echo", "hello")
      assert.equal(0, rc)
      assert.equal("hello\n", out)
    end)

    it("returns 1 for unknown applet", function()
      local rc, _, err = helpers.invoke_wrapper("nosuchapplet")
      assert.equal(1, rc)
      assert.is_truthy(err:match("unknown applet"))
    end)

    it("intercepts --help <applet>", function()
      local rc, out = helpers.invoke_wrapper("--help", "echo")
      assert.equal(0, rc)
      assert.is_truthy(out:match("^echo %-"))
    end)

    it("intercepts <applet> --help", function()
      local rc, out = helpers.invoke_wrapper("echo", "--help")
      assert.equal(0, rc)
      assert.is_truthy(out:match("^echo %-"))
    end)

    it("--help with unknown applet falls back to top-level help", function()
      local rc, out = helpers.invoke_wrapper("--help", "nosuch")
      assert.equal(0, rc)
      assert.is_truthy(out:match("Usage:"))
    end)
  end)

  describe("multi-call mode", function()
    it("dispatches via argv0 stem", function()
      local rc, out = helpers.invoke_multicall("echo", "hello")
      assert.equal(0, rc)
      assert.equal("hello\n", out)
    end)

    it("strips .exe suffix from argv0", function()
      local rc, out = helpers.invoke({ [0] = "echo.exe", [1] = "x" })
      assert.equal(0, rc)
      assert.equal("x\n", out)
    end)

    it("strips .lua suffix from argv0", function()
      local rc, out = helpers.invoke({ [0] = "echo.lua", [1] = "x" })
      assert.equal(0, rc)
      assert.equal("x\n", out)
    end)

    it("handles directory in argv0", function()
      local rc, out = helpers.invoke({ [0] = "/usr/local/bin/echo", [1] = "x" })
      assert.equal(0, rc)
      assert.equal("x\n", out)
    end)

    it("intercepts --help in multi-call mode", function()
      local rc, out = helpers.invoke_multicall("echo", "--help")
      assert.equal(0, rc)
      assert.is_truthy(out:match("^echo %-"))
    end)

    it("propagates exit code from applet", function()
      local rc = helpers.invoke_multicall("false")
      assert.equal(1, rc)
    end)
  end)
end)
