describe("lpeg + re vendoring", function()
  it("require('lpeg') succeeds and exposes version", function()
    local ok, lpeg = pcall(require, "lpeg")
    assert.is_true(ok, "lpeg must be available — install via 'luarocks install --local lpeg'")
    assert.is_string(lpeg.version)
    assert.is_truthy(lpeg.version:match("^LPeg"))
  end)

  it("require('vendor.re') succeeds and exposes compile", function()
    local ok, re = pcall(require, "vendor.re")
    assert.is_true(ok, "vendor/re.lua must be loadable")
    assert.is_function(re.compile)
    assert.is_function(re.match)
  end)

  it("re.compile parses a simple pattern", function()
    local re = require("vendor.re")
    local p = re.compile("[a-z]+")
    -- match returns the position after the match (or nil on no match)
    assert.equal(4, p:match("abc"))
    assert.is_nil(p:match("XYZ"))
  end)

  it("re alternation via ' / ' (LPeg's choice operator)", function()
    local re = require("vendor.re")
    local p = re.compile("'foo' / 'bar'")
    assert.is_truthy(p:match("foo"))
    assert.is_truthy(p:match("bar"))
    assert.is_nil(p:match("baz"))
  end)

  it("re captures via {} or unsugared", function()
    local re = require("vendor.re")
    local p = re.compile("{[0-9]+}")
    assert.equal("123", p:match("123abc"))
  end)
end)
