local regex = require("regex")

describe("regex (ERE-on-LPeg)", function()
  it("matches literals", function()
    local s, e = regex.find("hello", "say hello world")
    assert.equal(5, s)
    assert.equal(9, e)
  end)

  it("matches anchors", function()
    assert.is_truthy(regex.find("^abc", "abc def"))
    assert.is_nil(regex.find("^abc", "z abc"))
    assert.is_truthy(regex.find("xyz$", "wxyz"))
    assert.is_nil(regex.find("xyz$", "xyz!"))
  end)

  it("matches alternation", function()
    assert.is_truthy(regex.find("foo|bar", "we want bar"))
    assert.is_truthy(regex.find("foo|bar", "the foo there"))
    assert.is_nil(regex.find("foo|bar", "neither here"))
  end)

  it("matches char classes", function()
    local s = regex.find("[0-9]+", "abc123def")
    assert.equal(4, s)
    assert.is_nil(regex.find("[^0-9]+$", "abc123"))
  end)

  it("matches POSIX classes", function()
    local s, e = regex.find("[[:alpha:]]+", "  hello42")
    assert.equal(3, s)
    assert.equal(7, e)
    assert.is_truthy(regex.find("[[:digit:]]+", "abc12"))
  end)

  it("supports quantifiers", function()
    -- ? * + {n} {n,} {n,m}
    assert.is_truthy(regex.find("a?b", "b"))
    assert.is_truthy(regex.find("a?b", "ab"))
    assert.is_truthy(regex.find("ca*t", "ct"))
    assert.is_truthy(regex.find("ca*t", "caaaat"))
    local s, e = regex.find("ca+t", "caat")
    assert.equal(1, s)
    assert.equal(4, e)
    assert.is_nil(regex.find("ca+t", "ct"))
    -- {n,m}
    assert.is_truthy(regex.find("a{2,4}", "aaa"))
    assert.is_nil(regex.find("a{2,4}", "a"))
  end)

  it("captures groups", function()
    local _, _, caps = regex.find("([a-z]+) ([a-z]+)", "hello world")
    assert.equal("hello", caps[1])
    assert.equal("world", caps[2])
  end)

  it("non-capturing groups don't add a capture", function()
    local _, _, caps = regex.find("(?:foo) (bar)", "foo bar")
    assert.equal(1, #caps)
    assert.equal("bar", caps[1])
  end)

  it("does case-insensitive matching", function()
    local pat = regex.compile("hello", { ignore_case = true })
    assert.is_truthy(pat:find("HELLO"))
    assert.is_truthy(pat:find("Hello"))
  end)

  it("does dot-matches-any-but-newline", function()
    assert.is_truthy(regex.find("a.b", "axb"))
    assert.is_nil(regex.find("a.b", "a\nb"))
  end)

  it("supports \\d \\w \\s escapes", function()
    assert.is_truthy(regex.find("\\d+", "abc 42 xyz"))
    assert.is_truthy(regex.find("\\w+", "  hello"))
    assert.is_truthy(regex.find("\\s+", "no space yes"))
  end)

  it("gsub replaces with backrefs", function()
    local out = regex.gsub("hello world", "(\\w+) (\\w+)", "\\2 \\1")
    assert.equal("world hello", out)
  end)

  it("gsub & expands to whole match", function()
    local out = regex.gsub("foo bar", "[a-z]+", "<&>")
    assert.equal("<foo> <bar>", out)
  end)

  it("gsub respects max_n", function()
    local out, n = regex.gsub("a a a a", "a", "X", 2)
    assert.equal("X X a a", out)
    assert.equal(2, n)
  end)

  it("gsub with replacement function", function()
    local out = regex.gsub("hello world", "(\\w+)", function(w)
      return w:upper()
    end)
    assert.equal("HELLO WORLD", out)
  end)

  it("rejects malformed patterns gracefully", function()
    assert.has_error(function()
      regex.compile("[abc")
    end)
    assert.has_error(function()
      regex.compile("\\")
    end)
    assert.has_error(function()
      regex.compile("(unclosed")
    end)
  end)
end)
