local helpers = require("helpers")

describe("echo applet", function()
  before_each(function()
    helpers.load_applets()
  end)

  it("prints argument with newline", function()
    local rc, out = helpers.invoke_multicall("echo", "hello")
    assert.equal(0, rc)
    assert.equal("hello\n", out)
  end)

  it("joins multiple arguments with spaces", function()
    local rc, out = helpers.invoke_multicall("echo", "hello", "world")
    assert.equal(0, rc)
    assert.equal("hello world\n", out)
  end)

  it("-n suppresses trailing newline", function()
    local rc, out = helpers.invoke_multicall("echo", "-n", "hello")
    assert.equal(0, rc)
    assert.equal("hello", out)
  end)

  it("-e interprets backslash escapes", function()
    local rc, out = helpers.invoke_multicall("echo", "-e", "a\\nb")
    assert.equal(0, rc)
    assert.equal("a\nb\n", out)
  end)

  it("-E disables backslash escapes (default)", function()
    local rc, out = helpers.invoke_multicall("echo", "-E", "a\\nb")
    assert.equal(0, rc)
    assert.equal("a\\nb\n", out)
  end)

  it("combines flags: -ne", function()
    local rc, out = helpers.invoke_multicall("echo", "-ne", "a\\tb")
    assert.equal(0, rc)
    assert.equal("a\tb", out)
  end)

  it("prints empty line for no args", function()
    local rc, out = helpers.invoke_multicall("echo")
    assert.equal(0, rc)
    assert.equal("\n", out)
  end)

  it("treats unknown flags as text", function()
    local rc, out = helpers.invoke_multicall("echo", "-x", "y")
    assert.equal(0, rc)
    assert.equal("-x y\n", out)
  end)

  it("treats bare - as text", function()
    local rc, out = helpers.invoke_multicall("echo", "-")
    assert.equal(0, rc)
    assert.equal("-\n", out)
  end)
end)
